/**
 * Generated by scripts/buildFixedCameraDataset.js from SAPOL's public
 * "Fixed camera locations" table - see that script for the full pipeline
 * and re-run instructions. Do not hand-edit; re-run the script instead.
 *
 * Only Mid Block (open-road fixed speed cameras) and P2P (point-to-point
 * average-speed cameras) and I/section (intersection combo cameras, which
 * also enforce speed) location types are included - SAPOL's PAC/Rail/MPDC
 * types enforce pedestrian-crossing/level-crossing/phone-use, not speed.
 */
import type { GeoPoint } from '../geo/types';

export type FixedSpeedCameraType = 'MID_BLOCK' | 'P2P' | 'INTERSECTION';

export interface FixedSpeedCamera {
  id: string;
  label: string;
  type: FixedSpeedCameraType;
  position: GeoPoint;
}

export const FIXED_SPEED_CAMERAS: FixedSpeedCamera[] = [
  {
    id: "sapol-48",
    label: "Kensington Road/Portrush Road, MARRYATVILLE",
    type: "INTERSECTION",
    position: {
      latitude: -34.929508,
      longitude: 138.641681
    }
  },
  {
    id: "sapol-49",
    label: "King William Road/Sir Edwin Smith Avenue, NORTH ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.912983,
      longitude: 138.600549
    }
  },
  {
    id: "sapol-50",
    label: "Tapleys Hill Road/West Lakes Boulevard SEATON",
    type: "INTERSECTION",
    position: {
      latitude: -34.894461,
      longitude: 138.508154
    }
  },
  {
    id: "sapol-51",
    label: "Greenhill Road/Hutt Road, ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.937935,
      longitude: 138.666954
    }
  },
  {
    id: "sapol-58",
    label: "North East Road/Sudholz Road, GILLES PLAINS",
    type: "INTERSECTION",
    position: {
      latitude: -34.856652,
      longitude: 138.654674
    }
  },
  {
    id: "sapol-59",
    label: "Sudholz Road/North East Road, GILLES PLAINS",
    type: "INTERSECTION",
    position: {
      latitude: -34.856652,
      longitude: 138.654674
    }
  },
  {
    id: "sapol-61",
    label: "Lower Nth East Road/Darley Road, PARADISE",
    type: "INTERSECTION",
    position: {
      latitude: -34.865938,
      longitude: 138.674656
    }
  },
  {
    id: "sapol-65",
    label: "West Terrace/Hindley Street, ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.947967,
      longitude: 138.653111
    }
  },
  {
    id: "sapol-67",
    label: "Henley Beach Road/Holbrooks Road, UNDERDALE",
    type: "INTERSECTION",
    position: {
      latitude: -34.914599,
      longitude: 138.548262
    }
  },
  {
    id: "sapol-69",
    label: "Glover Avenue/West Terrace, ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.947967,
      longitude: 138.653111
    }
  },
  {
    id: "sapol-75",
    label: "Panalatinga Road/Pimpala Road, WOODCROFT",
    type: "INTERSECTION",
    position: {
      latitude: -35.103711,
      longitude: 138.554173
    }
  },
  {
    id: "sapol-76",
    label: "Main South Road/Bains Road, MORPHETT VALE",
    type: "INTERSECTION",
    position: {
      latitude: -35.122048,
      longitude: 138.523185
    }
  },
  {
    id: "sapol-77",
    label: "Main South Road/Doctors Road, MORPHETT VALE",
    type: "INTERSECTION",
    position: {
      latitude: -35.122048,
      longitude: 138.523185
    }
  },
  {
    id: "sapol-78",
    label: "Adelaide Road/Maurice Road, MURRAY BRIDGE",
    type: "INTERSECTION",
    position: {
      latitude: -35.125419,
      longitude: 139.256531
    }
  },
  {
    id: "sapol-79",
    label: "Adelaide Road/Mannum Road, MURRAY BRIDGE",
    type: "INTERSECTION",
    position: {
      latitude: -35.120449,
      longitude: 139.272658
    }
  },
  {
    id: "sapol-80",
    label: "Playford Avenue/Elliott Street, WHYALLA",
    type: "INTERSECTION",
    position: {
      latitude: -33.030255,
      longitude: 137.569555
    }
  },
  {
    id: "sapol-81",
    label: "Norrie Avenue/Nicolson Avenue, WHYALLA PLAYFORD",
    type: "INTERSECTION",
    position: {
      latitude: -33.028044,
      longitude: 137.556023
    }
  },
  {
    id: "sapol-82",
    label: "Victoria Parade/Flinders Terrace, PORT AUGUSTA",
    type: "INTERSECTION",
    position: {
      latitude: -32.498817,
      longitude: 137.776312
    }
  },
  {
    id: "sapol-83",
    label: "Victoria Parade/Carlton Parade, PORT AUGUSTA",
    type: "INTERSECTION",
    position: {
      latitude: -32.486634,
      longitude: 137.7837
    }
  },
  {
    id: "sapol-84",
    label: "Commercial Street West/Wehl Street South, MOUNT GAMBIER",
    type: "INTERSECTION",
    position: {
      latitude: -37.825632,
      longitude: 140.771844
    }
  },
  {
    id: "sapol-85",
    label: "Commercial Street East/Crouch Street North, MOUNT GAMBIER",
    type: "INTERSECTION",
    position: {
      latitude: -37.833039,
      longitude: 140.78562
    }
  },
  {
    id: "sapol-86",
    label: "Sturt Street/Bay Road, MOUNT GAMBIER",
    type: "INTERSECTION",
    position: {
      latitude: -37.846514,
      longitude: 140.769163
    }
  },
  {
    id: "sapol-87",
    label: "Main North Road/Yorktown Road, ELIZABETH PARK",
    type: "INTERSECTION",
    position: {
      latitude: -34.707758,
      longitude: 138.678407
    }
  },
  {
    id: "sapol-91",
    label: "South Road/Ashwin Parade, TORRENSVILLE",
    type: "INTERSECTION",
    position: {
      latitude: -34.922695,
      longitude: 138.569613
    }
  },
  {
    id: "sapol-92",
    label: "Payneham Road/Nelson Street, STEPNEY",
    type: "INTERSECTION",
    position: {
      latitude: -34.912078,
      longitude: 138.629744
    }
  },
  {
    id: "sapol-93",
    label: "Payneham Road/Lower Portrush Road, MARDEN",
    type: "INTERSECTION",
    position: {
      latitude: -34.893238,
      longitude: 138.635146
    }
  },
  {
    id: "sapol-94",
    label: "Main South Road/Black Road, O'HALLORAN HILL",
    type: "INTERSECTION",
    position: {
      latitude: -35.054221,
      longitude: 138.559673
    }
  },
  {
    id: "sapol-97",
    label: "Waterloo Corner Road/Bagster Road, SALISBURY NORTH",
    type: "INTERSECTION",
    position: {
      latitude: -34.753002,
      longitude: 138.626384
    }
  },
  {
    id: "sapol-98",
    label: "Bridge Road/Montague Road, INGLE FARM",
    type: "INTERSECTION",
    position: {
      latitude: -34.827864,
      longitude: 138.647932
    }
  },
  {
    id: "sapol-102",
    label: "Sir Donald Bradman Drive/Brooker Terrace, HILTON",
    type: "INTERSECTION",
    position: {
      latitude: -34.931956,
      longitude: 138.567066
    }
  },
  {
    id: "sapol-105",
    label: "Main North Road/Fairfield Road, ELIZABETH GROVE",
    type: "INTERSECTION",
    position: {
      latitude: -34.731672,
      longitude: 138.675455
    }
  },
  {
    id: "sapol-106",
    label: "Sturt Road/Marion Road, BEDFORD PARK",
    type: "INTERSECTION",
    position: {
      latitude: -35.026265,
      longitude: 138.573085
    }
  },
  {
    id: "sapol-107",
    label: "Commercial Road/Grand Junction Road, PORT ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.852499,
      longitude: 138.505403
    }
  },
  {
    id: "sapol-108",
    label: "North Terrace/Frome Road, ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.960997,
      longitude: 138.619346
    }
  },
  {
    id: "sapol-109",
    label: "Bridge Road/McIntyre Road, GULFVIEW HEIGHTS",
    type: "INTERSECTION",
    position: {
      latitude: -34.805469,
      longitude: 138.666293
    }
  },
  {
    id: "sapol-112",
    label: "Regency Road/Main North Road, PROSPECT",
    type: "INTERSECTION",
    position: {
      latitude: -34.873005,
      longitude: 138.601849
    }
  },
  {
    id: "sapol-113",
    label: "Torrens Road/South Road, RENOWN PARK",
    type: "INTERSECTION",
    position: {
      latitude: -34.893743,
      longitude: 138.583985
    }
  },
  {
    id: "sapol-116",
    label: "Salisbury Highway/Kings Road, PARAFIELD GARDENS",
    type: "INTERSECTION",
    position: {
      latitude: -34.782721,
      longitude: 138.623298
    }
  },
  {
    id: "sapol-117",
    label: "Anzac Highway/Morphett Road, CAMDEN PARK",
    type: "INTERSECTION",
    position: {
      latitude: -34.970332,
      longitude: 138.544873
    }
  },
  {
    id: "sapol-118",
    label: "Grote Street/West Terrace, ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.947967,
      longitude: 138.653111
    }
  },
  {
    id: "sapol-119",
    label: "South Road/Torrens Road, RENOWN PARK",
    type: "INTERSECTION",
    position: {
      latitude: -34.893743,
      longitude: 138.583985
    }
  },
  {
    id: "sapol-120",
    label: "Main North Road/Regency Road, ENFIELD",
    type: "INTERSECTION",
    position: {
      latitude: -34.867549,
      longitude: 138.601606
    }
  },
  {
    id: "sapol-121",
    label: "Kings Road/Salisbury Highway, SALISBURY DOWNS",
    type: "INTERSECTION",
    position: {
      latitude: -34.781227,
      longitude: 138.629863
    }
  },
  {
    id: "sapol-123",
    label: "Dequetteville Terrace/Botanic Road, ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.933255,
      longitude: 138.620775
    }
  },
  {
    id: "sapol-126",
    label: "Stephen Terrace/Payneham Road, ST PETERS",
    type: "INTERSECTION",
    position: {
      latitude: -34.908695,
      longitude: 138.627269
    }
  },
  {
    id: "sapol-127",
    label: "Main North Road/Frost Road, SALISBURY SOUTH",
    type: "INTERSECTION",
    position: {
      latitude: -34.787267,
      longitude: 138.64228
    }
  },
  {
    id: "sapol-128",
    label: "West Terrace/Hindley Street, ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.947967,
      longitude: 138.653111
    }
  },
  {
    id: "sapol-131",
    label: "Portrush Road/Magill Road, NORWOOD",
    type: "INTERSECTION",
    position: {
      latitude: -34.915082,
      longitude: 138.634659
    }
  },
  {
    id: "sapol-132",
    label: "Fitzroy Terrace/Prospect Road, FITZROY",
    type: "INTERSECTION",
    position: {
      latitude: -34.898208,
      longitude: 138.594698
    }
  },
  {
    id: "sapol-134",
    label: "North East Road/Reservoir Road, MODBURY",
    type: "INTERSECTION",
    position: {
      latitude: -34.831324,
      longitude: 138.688392
    }
  },
  {
    id: "sapol-136",
    label: "Findon Road/Balcombe Avenue, FINDON",
    type: "INTERSECTION",
    position: {
      latitude: -34.905108,
      longitude: 138.532572
    }
  },
  {
    id: "sapol-139",
    label: "North East Road/Sudholz Road, HOLDEN HILL",
    type: "INTERSECTION",
    position: {
      latitude: -34.852419,
      longitude: 138.665924
    }
  },
  {
    id: "sapol-157",
    label: "Montague Road, INGLE FARM",
    type: "MID_BLOCK",
    position: {
      latitude: -34.827864,
      longitude: 138.647932
    }
  },
  {
    id: "sapol-158",
    label: "Frederick Road, ROYAL PARK",
    type: "MID_BLOCK",
    position: {
      latitude: -34.866843,
      longitude: 138.502903
    }
  },
  {
    id: "sapol-160",
    label: "Magill Road/Glynburn Road, ST MORRIS",
    type: "INTERSECTION",
    position: {
      latitude: -34.910711,
      longitude: 138.657979
    }
  },
  {
    id: "sapol-161",
    label: "Lower North East Road/Darley Road, PARADISE",
    type: "INTERSECTION",
    position: {
      latitude: -34.865938,
      longitude: 138.674656
    }
  },
  {
    id: "sapol-163",
    label: "Tapleys Hill Road/Grange Road, SEATON",
    type: "INTERSECTION",
    position: {
      latitude: -34.894461,
      longitude: 138.508154
    }
  },
  {
    id: "sapol-165",
    label: "Chandlers Hill Road, HAPPY VALLEY",
    type: "MID_BLOCK",
    position: {
      latitude: -35.085935,
      longitude: 138.605509
    }
  },
  {
    id: "sapol-169",
    label: "Grange Road, KIDMAN PARK",
    type: "MID_BLOCK",
    position: {
      latitude: -34.905806,
      longitude: 138.526861
    }
  },
  {
    id: "sapol-173",
    label: "Port Wakefield Road, PARALOWIE",
    type: "MID_BLOCK",
    position: {
      latitude: -34.769131,
      longitude: 138.599579
    }
  },
  {
    id: "sapol-185",
    label: "Salisbury Highway/Elder Smith Road, MAWSON LAKES",
    type: "INTERSECTION",
    position: {
      latitude: -34.80485,
      longitude: 138.615141
    }
  },
  {
    id: "sapol-191",
    label: "Main North Road/Womma Road, ELIZABETH NORTH",
    type: "INTERSECTION",
    position: {
      latitude: -34.702539,
      longitude: 138.681267
    }
  },
  {
    id: "sapol-193",
    label: "Montague Rd/Walkleys Rd, INGLE FARM",
    type: "INTERSECTION",
    position: {
      latitude: -34.827864,
      longitude: 138.647932
    }
  },
  {
    id: "sapol-194",
    label: "Port Wakefield Road/Globe Derby Drive, GLOBE DERBY PARK",
    type: "INTERSECTION",
    position: {
      latitude: -34.791078,
      longitude: 138.595776
    }
  },
  {
    id: "sapol-600",
    label: "Port Wakefield Highway, TWO WELLS",
    type: "P2P",
    position: {
      latitude: -34.636528,
      longitude: 138.530007
    }
  },
  {
    id: "sapol-601",
    label: "Port Wakefield Highway, PORT WAKEFIELD",
    type: "P2P",
    position: {
      latitude: -34.220461,
      longitude: 138.196928
    }
  },
  {
    id: "sapol-602",
    label: "Port Wakefield Highway, TWO WELLS TO PORT WAKEFIELD",
    type: "P2P",
    position: {
      latitude: -34.220461,
      longitude: 138.196928
    }
  },
  {
    id: "sapol-603",
    label: "Port Wakefield Highway, PORT WAKEFIELD",
    type: "P2P",
    position: {
      latitude: -34.220461,
      longitude: 138.196928
    }
  },
  {
    id: "sapol-604",
    label: "Port Wakefield Highway, TWO WELLS",
    type: "P2P",
    position: {
      latitude: -34.636528,
      longitude: 138.530007
    }
  },
  {
    id: "sapol-605",
    label: "Port Wakefield Highway, PORT WAKEFIELD TO TWO WELLS",
    type: "P2P",
    position: {
      latitude: -34.679169,
      longitude: 138.550891
    }
  },
  {
    id: "sapol-607",
    label: "Dukes Highway, COONALPYN",
    type: "P2P",
    position: {
      latitude: -35.69661,
      longitude: 139.857456
    }
  },
  {
    id: "sapol-608",
    label: "Dukes Highway, KI KI TO COONALPYN",
    type: "P2P",
    position: {
      latitude: -36.330814,
      longitude: 140.942877
    }
  },
  {
    id: "sapol-609",
    label: "Dukes Highway COONALPYN",
    type: "P2P",
    position: {
      latitude: -35.69661,
      longitude: 139.857456
    }
  },
  {
    id: "sapol-611",
    label: "Dukes Highway COONALPYN TO KI KI",
    type: "P2P",
    position: {
      latitude: -36.330814,
      longitude: 140.942877
    }
  },
  {
    id: "sapol-612",
    label: "Victor Harbor Road, MCLAREN VALE",
    type: "P2P",
    position: {
      latitude: -35.195792,
      longitude: 138.508352
    }
  },
  {
    id: "sapol-614",
    label: "Victor Harbor Road, MCLAREN VALE TO WILLUNGA",
    type: "P2P",
    position: {
      latitude: -35.195792,
      longitude: 138.508352
    }
  },
  {
    id: "sapol-617",
    label: "Victor Harbor Road, WHITES VALLEY TO TATACHILLA",
    type: "P2P",
    position: {
      latitude: -35.296365,
      longitude: 138.581006
    }
  },
  {
    id: "sapol-620",
    label: "South Eastern Freeway, NAIRNE TO CALLINGTON",
    type: "P2P",
    position: {
      latitude: -35.059079,
      longitude: 138.843924
    }
  },
  {
    id: "sapol-623",
    label: "South Eastern Freeway, CALLINGTON TO MOUNT BARKER SUMMIT",
    type: "P2P",
    position: {
      latitude: -35.059079,
      longitude: 138.843924
    }
  },
  {
    id: "sapol-624",
    label: "Sturt Highway, LOWBANK",
    type: "P2P",
    position: {
      latitude: -34.18863,
      longitude: 140.105562
    }
  },
  {
    id: "sapol-625",
    label: "Sturt Highway, WIGLEY FLAT",
    type: "P2P",
    position: {
      latitude: -34.192272,
      longitude: 140.283553
    }
  },
  {
    id: "sapol-626",
    label: "Sturt Highway, LOWBANK TO WIGLEY FLAT",
    type: "P2P",
    position: {
      latitude: -34.192272,
      longitude: 140.283553
    }
  },
  {
    id: "sapol-628",
    label: "Sturt Highway, KANNI",
    type: "P2P",
    position: {
      latitude: -34.219522,
      longitude: 140.041149
    }
  },
  {
    id: "sapol-629",
    label: "Sturt Highway, WOOLPUNDA TO KANNI",
    type: "P2P",
    position: {
      latitude: -32.479241,
      longitude: 137.752358
    }
  },
  {
    id: "sapol-632",
    label: "Northern Expressway, VIRGINIA TO WARD BELT",
    type: "P2P",
    position: {
      latitude: -34.659271,
      longitude: 138.656805
    }
  },
  {
    id: "sapol-635",
    label: "Northern Expressway, BUCHFELDE TO WATERLOO CORNER",
    type: "P2P",
    position: {
      latitude: -34.659271,
      longitude: 138.656805
    }
  },
  {
    id: "sapol-801",
    label: "South Eastern Freeway, LEAWOOD GARDENS",
    type: "MID_BLOCK",
    position: {
      latitude: -34.974842,
      longitude: 138.677673
    }
  },
  {
    id: "sapol-802",
    label: "South Eastern Freeway, LEAWOOD GARDENS",
    type: "MID_BLOCK",
    position: {
      latitude: -34.974842,
      longitude: 138.677673
    }
  },
  {
    id: "sapol-803",
    label: "South Eastern Freeway, LEAWOOD GARDENS",
    type: "MID_BLOCK",
    position: {
      latitude: -34.974842,
      longitude: 138.677673
    }
  },
  {
    id: "sapol-88",
    label: "Main North Road/Yorketown Road M/S, ELIZABETH PARK",
    type: "INTERSECTION",
    position: {
      latitude: -34.707758,
      longitude: 138.678407
    }
  },
  {
    id: "sapol-99",
    label: "Glover Avenue, ADELAIDE",
    type: "MID_BLOCK",
    position: {
      latitude: -34.828111,
      longitude: 138.616205
    }
  },
  {
    id: "sapol-108",
    label: "North Terrace/Frome Road, ADELAIDE",
    type: "INTERSECTION",
    position: {
      latitude: -34.960997,
      longitude: 138.619346
    }
  },
  {
    id: "sapol-113",
    label: "Torrens Road/South Road, RENOWN PARK",
    type: "INTERSECTION",
    position: {
      latitude: -34.893743,
      longitude: 138.583985
    }
  },
  {
    id: "sapol-119",
    label: "South Road/Torrens Road, RENOWN PARK",
    type: "INTERSECTION",
    position: {
      latitude: -34.893743,
      longitude: 138.583985
    }
  },
  {
    id: "sapol-156",
    label: "South Eastern Freeway, LEAWOOD GARDENS",
    type: "MID_BLOCK",
    position: {
      latitude: -34.974842,
      longitude: 138.677673
    }
  }
];
